<?php
namespace Probe\Concerns;


trait HasStub{
    /**
     * Stub name
     */
    abstract public static function stub(): string;

    /**
     * Namespace to use when making from stub
     */
    abstract public static function namespace(): string;

    /**
     * Folder name that is used to store the new file that is generated by the `make command`.
     */
    abstract public static function folder(): string;
}